# Generated by Django 5.2.11 on 2026-09-05 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='enrollment_date',
        ),
    ]
