# Generated by Django 5.2.11 on 2026-09-09 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='ttile',
            new_name='title',
        ),
    ]
